[theme]
base = "light"
primaryColor = "#1F5F8B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F5F8"
textColor = "#1B2733"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
